name: "Deploy to Cloud Run"

on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'

    name: "Deploy to Cloud Run"
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: gcr.io/${{secrets.GCP_PROJECT_ID}}/${{vars.INSTANCE_NAME}}:${{github.sha}}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Authenticate with Google Cloud"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: "Setup Google Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1

      - name: "Configure Docker"
        run: gcloud auth configure-docker --quiet

      - name: "Build Docker Image"
        run: docker build -t $DOCKER_IMAGE .

      - name: "Push Docker Image"
        run: docker push $DOCKER_IMAGE

      - name: "Deploy to Cloud Run"
        run: |
          gcloud run deploy ${{vars.INSTANCE_NAME}} \
              --image $DOCKER_IMAGE \
              --platform managed \
              --region ${{vars.INSTANCE_REGION}} \
              --allow-unauthenticated \
              --service-account ${{secrets.GCP_CLOUD_RUN_SA_EMAIL}} \
